# Generated by Django 4.2 on 2023-04-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='registrador_por',
            new_name='registrado_por',
        ),
    ]
